spring:
  profiles: 
    active: dev2
---
server:
  port: 8082
spring:
  application:
    name: servicecloud-config-dev2
  profiles: dev2
 
---
server:
  port: 80
spring:
  application:
    name: servicecloud-config-prod
  profiles: prod