spring:
  profiles: 
    active: dev2
---
server:
  port: 8082
spring:
  application:
    name: servicecloud-config-dev2
  profiles: dev2
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registy: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
 
---
server:
  port: 80
spring:
  application:
    name: servicecloud-config-prod
  profiles: prod
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registy: false
    service-url:
      defaultZone: http://localhost:7001/eureka/