spring:
  profiles: 
    active: dev2
---
server:
  port: 7001
spring:
  application:
    name: servicecloud-eureka-config
  profiles: dev2
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registy: false
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
 
---
server:
  port: 7002
spring:
  application:
    name: servicecloud-eureka-config
  profiles: prod
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registy: false
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/